# Generated by Django 5.2.6 on 2026-07-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_prova', models.CharField(blank=True, max_length=500)),
                ('arquivo_gabarito', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('sucesso', 'Concluída'), ('parcial', 'Concluída com questões descartadas'), ('erro', 'Falhou')], max_length=10)),
                ('questoes_detectadas', models.PositiveSmallIntegerField(default=0)),
                ('questoes_importadas', models.PositiveSmallIntegerField(default=0)),
                ('descartes', models.JSONField(blank=True, default=list)),
                ('mensagem', models.TextField(blank=True)),
                ('executada_em', models.DateTimeField(auto_now_add=True)),
                ('prova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestoes', to='catalogo.prova')),
            ],
            options={
                'verbose_name': 'ingestão',
                'verbose_name_plural': 'ingestões',
                'ordering': ['-executada_em'],
            },
        ),
    ]
