# Generated by Django 5.2.6 on 2026-07-27 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('slug', models.SlugField(max_length=120, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")])),
                ('tipo', models.CharField(choices=[('oficial', 'Documento oficial da banca ou do órgão'), ('amostra', 'Amostra escrita para o protótipo'), ('derivada', 'Derivada de documento oficial (resumo/reorganização)')], max_length=10)),
                ('titulo', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, help_text='Endereço do documento de origem.', max_length=500)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('publicado_em', models.DateField(blank=True, null=True)),
                ('obtido_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'fonte',
                'verbose_name_plural': 'fontes',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")])),
                ('nome', models.CharField(max_length=300)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'subtópico',
                'verbose_name_plural': 'subtópicos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.SlugField(max_length=60, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")])),
                ('nome', models.CharField(max_length=160)),
                ('cor', models.CharField(help_text='Cor da disciplina no gráfico, em hex.', max_length=7)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='catalogo.fonte')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")])),
                ('ano', models.PositiveSmallIntegerField()),
                ('banca', models.CharField(max_length=80)),
                ('cargo', models.CharField(max_length=200)),
                ('orgao', models.CharField(max_length=200)),
                ('qtd_questoes', models.PositiveSmallIntegerField()),
                ('url_prova', models.URLField(blank=True, max_length=500)),
                ('url_gabarito', models.URLField(blank=True, max_length=500)),
                ('aplicada_em', models.DateField(blank=True, null=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provas', to='catalogo.fonte')),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
                'ordering': ['-ano', 'orgao'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.SlugField(max_length=120, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")])),
                ('numero_na_prova', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ano', models.PositiveSmallIntegerField()),
                ('banca', models.CharField(max_length=80)),
                ('texto_base', models.TextField(blank=True)),
                ('enunciado', models.TextField()),
                ('correta', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('explicacao', models.TextField(blank=True)),
                ('anulada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='catalogo.disciplina')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='catalogo.fonte')),
                ('prova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='catalogo.prova')),
                ('subtopico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='catalogo.subtopico')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['-ano', 'prova_id', 'numero_na_prova'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")])),
                ('nome', models.CharField(max_length=300)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='catalogo.disciplina')),
            ],
            options={
                'verbose_name': 'tópico',
                'verbose_name_plural': 'tópicos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='subtopico',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='catalogo.topico'),
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('texto', models.TextField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='catalogo.questao')),
            ],
            options={
                'verbose_name': 'alternativa',
                'verbose_name_plural': 'alternativas',
                'ordering': ['letra'],
                'constraints': [models.UniqueConstraint(fields=('questao', 'letra'), name='alternativa_unica_por_letra')],
            },
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['disciplina', 'ano'], name='catalogo_qu_discipl_183a63_idx'),
        ),
        migrations.AddConstraint(
            model_name='questao',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_na_prova__isnull', False), ('prova__isnull', False)), fields=('prova', 'numero_na_prova'), name='questao_unica_por_numero_na_prova'),
        ),
    ]
