# Generated by Django 5.2.6 on 2026-07-28 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_questao_topico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurso_id', models.SlugField(max_length=80, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")])),
                ('conteudo_markdown', models.TextField()),
                ('gerado_em', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(blank=True, help_text='Qual IA gerou, para dar o que invalidar se o modelo mudar.', max_length=120)),
                ('subtopico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='catalogo.subtopico')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='catalogo.topico')),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
                'ordering': ['topico_id', 'subtopico_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('subtopico__isnull', False)), fields=('topico', 'subtopico', 'concurso_id'), name='aula_unica_por_unidade_com_subtopico'), models.UniqueConstraint(condition=models.Q(('subtopico__isnull', True)), fields=('topico', 'concurso_id'), name='aula_unica_por_unidade_sem_subtopico')],
            },
        ),
    ]
