# Generated by Django 5.2.6 on 2026-07-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='pontuacao_liquida',
            field=models.BooleanField(default=False, help_text='Se marcado, cada erro anula um acerto (padrão Cebraspe).'),
        ),
        migrations.AddField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('multipla', 'Múltipla escolha (A–E)'), ('certo_errado', 'Certo ou errado')], default='multipla', max_length=12),
        ),
    ]
