# Generated by Django 5.2.6 on 2026-07-28 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_prova_pontuacao_liquida_questao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='concurso_id',
            field=models.SlugField(default='bb-ti-2026', max_length=80, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")]),
        ),
        migrations.AlterField(
            model_name='topico',
            name='id',
            field=models.SlugField(max_length=120, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")]),
        ),
        migrations.AddIndex(
            model_name='topico',
            index=models.Index(fields=['concurso_id', 'disciplina'], name='catalogo_to_concurs_347893_idx'),
        ),
    ]
