# Generated by Django 5.2.6 on 2026-08-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_topico_concurso_id_alter_topico_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopico',
            name='ativo_edital_vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subtopico',
            name='edital_ref',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topico',
            name='ativo_edital_vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topico',
            name='edital_ref',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
