# Generated by Django 5.2.6 on 2026-08-05 04:04

from django.db import migrations


def preencher_edital_ref(apps, schema_editor):
    """edital_ref = numeração do item no edital. Para os tópicos já importados,
    a numeração é a própria `ordem` (1-based) dentro da disciplina; para
    subtópicos, "<ordem do tópico>.<ordem do subtópico>" — mesmo padrão que
    `importar_edital` passa a gravar para itens novos daqui pra frente."""
    Topico = apps.get_model("catalogo", "Topico")
    Subtopico = apps.get_model("catalogo", "Subtopico")

    for topico in Topico.objects.all():
        topico.edital_ref = str(topico.ordem)
        topico.save(update_fields=["edital_ref"])

    for sub in Subtopico.objects.select_related("topico").all():
        sub.edital_ref = f"{sub.topico.ordem}.{sub.ordem}"
        sub.save(update_fields=["edital_ref"])


def limpar_edital_ref(apps, schema_editor):
    Topico = apps.get_model("catalogo", "Topico")
    Subtopico = apps.get_model("catalogo", "Subtopico")
    Topico.objects.update(edital_ref="")
    Subtopico.objects.update(edital_ref="")


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_adiciona_edital_ref_e_ativo_vigente'),
    ]

    operations = [
        migrations.RunPython(preencher_edital_ref, limpar_edital_ref),
    ]
