# Generated by Django 5.2.6 on 2026-08-05 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_backfill_edital_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eh_primaria', models.BooleanField(default=True)),
                ('nivel_cognitivo', models.CharField(blank=True, choices=[('memorizacao', 'Memorização'), ('compreensao', 'Compreensão'), ('aplicacao', 'Aplicação'), ('analise', 'Análise')], max_length=20)),
                ('formato_item', models.CharField(blank=True, choices=[('conceitual', 'Conceitual'), ('leitura_de_codigo', 'Leitura de código'), ('calculo', 'Cálculo'), ('interpretacao_de_caso', 'Interpretação de caso'), ('comando_sintaxe', 'Comando/sintaxe')], max_length=25)),
                ('confianca', models.FloatField(default=1.0, help_text='0.0–1.0. Só é 1.0 de verdade quando origem=humana.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('origem_classificacao', models.CharField(choices=[('humana', 'Humana'), ('heuristica', 'Heurística (termo-âncora)'), ('llm_externa', 'IA externa (não embutida no app)')], max_length=12)),
                ('justificativa', models.TextField(blank=True)),
                ('revisada_por_humano', models.BooleanField(default=False)),
                ('revisada_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='catalogo.questao')),
                ('subtopico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classificacoes', to='catalogo.subtopico')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classificacoes', to='catalogo.topico')),
            ],
            options={
                'verbose_name': 'classificação de questão',
                'verbose_name_plural': 'classificações de questão',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['origem_classificacao', 'revisada_por_humano'], name='catalogo_cl_origem__ad0d0b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('eh_primaria', True)), fields=('questao',), name='uma_classificacao_primaria_por_questao')],
            },
        ),
    ]
