# Generated by Django 5.2.6 on 2026-08-05 18:27

from django.db import migrations


def preencher_classificacao(apps, schema_editor):
    """Cria a linha primária em ClassificacaoQuestao para toda questão que já
    tinha `topico` preenchido antes desta tabela existir.

    origem="humana" é uma suposição documentada, não um fato verificado: essas
    232 classificações vieram de arquivos JSON em `backend/classificacoes/`,
    aplicados por `classificar_questoes` — um processo que sempre exigiu alguém
    curar o arquivo antes de rodar o comando, mesmo que o conteúdo original
    tenha nascido de uma IA externa colada e aceita por essa pessoa. Não há
    registro de qual foi o caso pra cada questão, então fica com a leitura mais
    honesta disponível: revisada e aceita por humano no momento em que entrou.
    """
    Questao = apps.get_model("catalogo", "Questao")
    ClassificacaoQuestao = apps.get_model("catalogo", "ClassificacaoQuestao")

    classificadas = Questao.objects.filter(topico__isnull=False).only("id", "topico_id", "subtopico_id")
    ClassificacaoQuestao.objects.bulk_create(
        ClassificacaoQuestao(
            questao_id=q.id,
            topico_id=q.topico_id,
            subtopico_id=q.subtopico_id,
            eh_primaria=True,
            confianca=1.0,
            origem_classificacao="humana",
            revisada_por_humano=True,
        )
        for q in classificadas
    )


def limpar_classificacao(apps, schema_editor):
    ClassificacaoQuestao = apps.get_model("catalogo", "ClassificacaoQuestao")
    ClassificacaoQuestao.objects.filter(origem_classificacao="humana", justificativa="").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_adiciona_classificacao_questao'),
    ]

    operations = [
        migrations.RunPython(preencher_classificacao, limpar_classificacao),
    ]
