# Generated by Django 5.2.6 on 2026-08-05 21:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_backfill_classificacao_existente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('slug', models.SlugField(max_length=60, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")])),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'banca',
                'verbose_name_plural': 'bancas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*$', "Use apenas minúsculas, números e hífen (ex.: 'bb-ti-2023').")])),
                ('nome', models.CharField(max_length=200)),
                ('orgao', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('data_prova', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inscricoes_abertas', 'Inscrições abertas'), ('inscricoes_encerradas', 'Inscrições encerradas'), ('previsto', 'Previsto'), ('encerrado', 'Encerrado')], max_length=24)),
                ('banca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concursos', to='catalogo.banca')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concursos', to='catalogo.fonte')),
            ],
            options={
                'verbose_name': 'concurso',
                'verbose_name_plural': 'concursos',
                'ordering': ['-data_prova', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='prova',
            name='concurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provas', to='catalogo.concurso'),
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveSmallIntegerField(default=1)),
                ('eh_vigente', models.BooleanField(default=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editais', to='catalogo.concurso')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editais', to='catalogo.fonte')),
            ],
            options={
                'verbose_name': 'edital',
                'verbose_name_plural': 'editais',
                'ordering': ['-versao'],
            },
        ),
        migrations.CreateModel(
            name='ItemEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao_original', models.CharField(max_length=20)),
                ('redacao_literal', models.TextField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='catalogo.edital')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_edital', to='catalogo.topico')),
            ],
            options={
                'verbose_name': 'item do edital',
                'verbose_name_plural': 'itens do edital',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='edital',
            constraint=models.UniqueConstraint(condition=models.Q(('eh_vigente', True)), fields=('concurso',), name='um_edital_vigente_por_concurso'),
        ),
        migrations.AddConstraint(
            model_name='itemedital',
            constraint=models.UniqueConstraint(fields=('edital', 'topico'), name='item_edital_unico_por_topico'),
        ),
    ]
