# Generated by Django 5.2.6 on 2026-08-05 21:18

from django.db import migrations

# Espelha, campo a campo, o que já está em `src/data/concursos.ts` — não é dado
# novo, é o mesmo catálogo do frontend agora também no backend. Escopo restrito
# aos 3 concursos que têm prova real importada; ver docstring de `Concurso`.
FONTES = [
    {
        "slug": "bb-2026-situacao",
        "tipo": "amostra",
        "titulo": (
            "Situação do concurso BB 2026: contrato com a Cesgranrio encerrado, "
            "banca em definição"
        ),
        "url": "https://blog.grancursosonline.com.br/concurso-banco-do-brasil-contrato-cesgranrio-encerrado-2026/",
        "publicado_em": "2026-01-13",
    },
    {
        "slug": "treino-de-formato",
        "tipo": "derivada",
        "titulo": "Prova anterior de outro órgão, no catálogo para treinar o estilo da banca",
        "url": "",
        "publicado_em": None,
    },
]

BANCAS = [
    {"slug": "cesgranrio", "nome": "Cesgranrio"},
    {"slug": "cebraspe", "nome": "Cebraspe"},
    {"slug": "fgv", "nome": "FGV"},
]

CONCURSOS = [
    {
        "slug": "bb-ti-2026",
        "nome": "Banco do Brasil — Agente de Tecnologia",
        "orgao": "Banco do Brasil",
        "cargo": "Escriturário — Agente de Tecnologia",
        "banca_slug": None,
        "data_prova": None,
        "status": "previsto",
        "fonte_slug": "bb-2026-situacao",
        "provas": [
            "bb-ti-2023",
            "bb-comercial-a-2023",
            "bb-comercial-b-2023",
            "bb-comercial-c-2023",
            "bb-2021-a",
            "bb-2021-b",
            "bb-2021-c",
        ],
    },
    {
        "slug": "fgv-banestes-ti-2021",
        "nome": "Banestes 2021 — Analista de TI (treino FGV)",
        "orgao": "Banco do Estado do Espírito Santo",
        "cargo": "Analista em Tecnologia da Informação - Desenvolvimento de Sistemas",
        "banca_slug": "fgv",
        "data_prova": "2021-12-19",
        "status": "encerrado",
        "fonte_slug": "treino-de-formato",
        "provas": ["fgv-banestes-ti-2021"],
    },
    {
        "slug": "cebraspe-bnb-ti-2022",
        "nome": "BNB 2022 — Analista de Sistemas (treino Cebraspe)",
        "orgao": "Banco do Nordeste do Brasil",
        "cargo": "Especialista Técnico — Analista de Sistemas",
        "banca_slug": "cebraspe",
        "data_prova": "2022-12-04",
        "status": "encerrado",
        "fonte_slug": "treino-de-formato",
        "provas": ["cebraspe-bnb-ti-2022"],
    },
]

# Fonte já criada por `manage.py importar_edital --slug edital-bb-2022-001`.
# Só o concurso bb-ti-2026 tem árvore de tópicos importada — ver
# `docs/auditoria-corpus.md`, não há edital de BNB/Banestes neste acervo.
FONTE_EDITAL_BB = "edital-bb-2022-001"
CONCURSO_COM_EDITAL = "bb-ti-2026"


def preencher(apps, schema_editor):
    Fonte = apps.get_model("catalogo", "Fonte")
    Banca = apps.get_model("catalogo", "Banca")
    Concurso = apps.get_model("catalogo", "Concurso")
    Prova = apps.get_model("catalogo", "Prova")
    Edital = apps.get_model("catalogo", "Edital")
    ItemEdital = apps.get_model("catalogo", "ItemEdital")
    Topico = apps.get_model("catalogo", "Topico")

    for dados in FONTES:
        Fonte.objects.update_or_create(slug=dados["slug"], defaults={k: v for k, v in dados.items() if k != "slug"})

    for dados in BANCAS:
        Banca.objects.update_or_create(slug=dados["slug"], defaults={"nome": dados["nome"]})

    for dados in CONCURSOS:
        concurso, _ = Concurso.objects.update_or_create(
            slug=dados["slug"],
            defaults={
                "nome": dados["nome"],
                "orgao": dados["orgao"],
                "cargo": dados["cargo"],
                "banca_id": dados["banca_slug"],
                "data_prova": dados["data_prova"],
                "status": dados["status"],
                "fonte_id": dados["fonte_slug"],
            },
        )
        Prova.objects.filter(id__in=dados["provas"]).update(concurso=concurso)

    concurso_bb = Concurso.objects.filter(slug=CONCURSO_COM_EDITAL).first()
    fonte_edital = Fonte.objects.filter(slug=FONTE_EDITAL_BB).first()
    if concurso_bb and fonte_edital:
        edital, _ = Edital.objects.update_or_create(
            concurso=concurso_bb,
            versao=1,
            defaults={"fonte": fonte_edital, "eh_vigente": True},
        )
        for topico in Topico.objects.filter(concurso_id=CONCURSO_COM_EDITAL):
            ItemEdital.objects.update_or_create(
                edital=edital,
                topico=topico,
                defaults={
                    "numeracao_original": topico.edital_ref,
                    "redacao_literal": topico.nome,
                    "ordem": topico.ordem,
                },
            )


def limpar(apps, schema_editor):
    Concurso = apps.get_model("catalogo", "Concurso")
    Prova = apps.get_model("catalogo", "Prova")
    Prova.objects.filter(concurso__slug__in=[c["slug"] for c in CONCURSOS]).update(concurso=None)
    Concurso.objects.filter(slug__in=[c["slug"] for c in CONCURSOS]).delete()
    Banca = apps.get_model("catalogo", "Banca")
    Banca.objects.filter(slug__in=[b["slug"] for b in BANCAS]).delete()
    Fonte = apps.get_model("catalogo", "Fonte")
    Fonte.objects.filter(slug__in=[f["slug"] for f in FONTES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_modela_concurso_edital'),
    ]

    operations = [
        migrations.RunPython(preencher, limpar),
    ]
