# Generated by Django 5.2.6 on 2026-08-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_backfill_concurso_edital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['topico_id', 'subtopico_id', '-versao'], 'verbose_name': 'aula', 'verbose_name_plural': 'aulas'},
        ),
        migrations.RemoveConstraint(
            model_name='aula',
            name='aula_unica_por_unidade_com_subtopico',
        ),
        migrations.RemoveConstraint(
            model_name='aula',
            name='aula_unica_por_unidade_sem_subtopico',
        ),
        migrations.AddField(
            model_name='aula',
            name='prompt_versao',
            field=models.CharField(blank=True, help_text='Versão do prompt que gerou (PROMPT_AULA_VERSAO no frontend). É o que permite saber quais aulas são de uma geração antiga do prompt.', max_length=40),
        ),
        migrations.AddField(
            model_name='aula',
            name='substituida_em',
            field=models.DateTimeField(blank=True, help_text='Nulo = esta é a versão corrente.', null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='versao',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aula',
            name='gerado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(condition=models.Q(('substituida_em__isnull', True), ('subtopico__isnull', False)), fields=('topico', 'subtopico', 'concurso_id'), name='aula_corrente_unica_com_subtopico'),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(condition=models.Q(('substituida_em__isnull', True), ('subtopico__isnull', True)), fields=('topico', 'concurso_id'), name='aula_corrente_unica_sem_subtopico'),
        ),
    ]
