# Generated by Django 5.2.6 on 2026-08-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_aula_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gabarito_errado', 'Gabarito errado'), ('enunciado_incompleto', 'Enunciado incompleto ou truncado'), ('alternativa_faltando', 'Alternativa faltando ou vazia'), ('classificacao_errada', 'Assunto/classificação errada'), ('outro', 'Outro')], max_length=24)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, help_text='Nulo = ainda na fila de curadoria.', null=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='catalogo.questao')),
            ],
            options={
                'verbose_name': 'problema de questão',
                'verbose_name_plural': 'problemas de questão',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['resolvido_em'], name='catalogo_pr_resolvi_823fa8_idx')],
            },
        ),
    ]
