# Generated by Django 5.2.6 on 2026-08-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_problemaquestao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concurso',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'concurso', 'verbose_name_plural': 'concursos'},
        ),
        migrations.AddField(
            model_name='concurso',
            name='edital_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='concurso',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concurso',
            name='salario_observacao',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='concurso',
            name='salario_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='concurso',
            name='vagas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fonte',
            name='rotulo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
